apiVersion: v1
data:
  private_dns_zone_name: qa-us-west-2
  private_lb_security_group_id: sg-0e51c9adf3f97741a
  public_dns_zone_name: qa.skillz.com
  public_lb_security_group_id: sg-04b8f6725f9387552
  rds_endpoint: islay-ejabberd-t1-1.cgxoaw9qeixu.us-west-2.rds.amazonaws.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"private_dns_zone_name":"qa-us-west-2","private_lb_security_group_id":"sg-0e51c9adf3f97741a","public_dns_zone_name":"qa.skillz.com","public_lb_security_group_id":"sg-04b8f6725f9387552","rds_endpoint":"islay-ejabberd-t1-1.cgxoaw9qeixu.us-west-2.rds.amazonaws.com"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2019-10-17T14:42:50Z","name":"tf-ejabberd-external","namespace":"server","resourceVersion":"4830861","selfLink":"/api/v1/namespaces/server/configmaps/tf-ejabberd-external","uid":"64c55919-f0ec-11e9-a95a-0207bc78979c"}}
  creationTimestamp: "2019-10-17T14:42:50Z"
  name: tf-ejabberd-external
  namespace: server
  resourceVersion: "4831564"
  selfLink: /api/v1/namespaces/server/configmaps/tf-ejabberd-external
  uid: 64c55919-f0ec-11e9-a95a-0207bc78979c
