apiVersion: v1
kind: Service
metadata:
  name: $(SVC_NAME_EXTERNAL)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  ports: # Basically only keep the websocket port
  - name: http
    $patch: delete
  - name: c2s
    $patch: delete
  - name: s2s-in
    $patch: delete