apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-service
  name: $(SVC_NAME_ADMIN)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: $(PRIVATE_ELB_SG)
    external-dns.alpha.kubernetes.io/hostname: $(SVC_NAME_ADMIN).$(PRIVATE_DNS_ZONE_NAME)
spec:
  selector:
    app: chat-service
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: c2s
    port: 5222
    targetPort: c2s
