apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-service
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: $(IAM_ROLE)
    spec:
      containers:
      - name: ejabberd
        image: $(ECR_REPOSITORY):latest
        command: ["/opt/chat-service/scripts/run.sh", "${NUM_K8S_REPLICAS}", "&&", "sleep 10000"]
        volumeMounts:
          - name: ejabberd-config
            mountPath: /opt/chat-service/etc/ejabberd/authentication.yaml
            subPath: authentication.yaml