apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-service
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: $(IAM_ROLE)
    spec:
      containers:
      - name: ejabberd
        image: $(ECR_REPOSITORY):qa
        imagePullPolicy: Always
        volumeMounts:
          - name: ejabberd-config
            mountPath: /opt/chat-service/etc/ejabberd/authentication.yaml
            subPath: authentication.yaml
