namespace: server
configurations:
- varconfig.yaml
resources:
- stateful-set.yaml
- namespace.yaml
- secret.yaml
- service-account.yaml
- service-external.yaml
- service-internal-discovery.yaml
configMapGenerator:
- name: chat-service-config
  literals:
  - num_ejabberd_replicas=3
  - service_name_external=chat-service-external
  - service_name_internal=chat-service-internal
- name: ejabberd-config
  files:
  - config/inetrc
  - config/ejabberd.yaml
  - config/log.yaml
  - config/hosts.yaml
  - config/listen.yaml
  - config/api-permissions.yaml
  - config/access-rules.yaml
  - config/access-control-lists.yaml
  - config/modules.yaml
- name: ejabberd-vault-config
  files:
  - config/consul-template-config.hcl
  - config/vault-agent-config.hcl
vars:
- name: NUM_REPLICAS
  objref:
    kind: ConfigMap
    name: chat-service-config
    apiVersion: v1
  fieldref:
    fieldpath: data.num_ejabberd_replicas
- name: SVC_NAME_INTERNAL
  objref:
    kind: ConfigMap
    name: chat-service-config
    apiVersion: v1
  fieldref:
    fieldpath: data.service_name_internal
- name: SVC_NAME_EXTERNAL
  objref:
    kind: ConfigMap
    name: chat-service-config
    apiVersion: v1
  fieldref:
    fieldpath: data.service_name_external
