namespace: server
resources:
- deployment.yaml
- namespace.yaml
- secret.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: ejabberd-config
  files:
  - config/ejabberdctl.cfg
  - config/inetrc
  - config/ejabberd.yaml
  - config/log.yaml
  - config/hosts.yaml
  - config/listen.yaml
  - config/api-permissions.yaml
  - config/access-rules.yaml
  - config/access-control-lists.yaml
  - config/modules.yaml
- name: ejabberd-vault-config
  files:
  - config/consul-template-config.hcl
  - config/vault-agent-config.hcl
secretGenerator:
- name: ejabberd-config-secret
  files:
  - secret/authentication.yaml
