apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-service
  name: chat-service
spec:
  selector:
    app: chat-service
  type: LoadBalancer
  ports:
  - name: http
    port: 5280
    targetPort: http
  - name: s2s-in
    port: 5269
    targetPort: s2s-in
  - name: c2s
    port: 5222
    targetPort: c2s
