##
## Modules enabled in all ejabberd virtual hosts.
##
modules:
  mod_blocking: {} # requires mod_privacy
  mod_block_incoming: {
    blocking_users: ["test2@localhost", "test3@localhost", "11339339@chat.skillz.com", "20361620@chat.skillz.com", "12669429@chat.skillz.com", "97789891@chat.skillz.com", "67115158@chat.skillz.com", "40890859@chat.skillz.com", "50447625@chat.skillz.com", "26581865@chat.skillz.com", "41241278@chat.skillz.com", "14462266@chat.skillz.com", "33411470@chat.skillz.com", "29450014@chat.skillz.com", "32704697@chat.skillz.com", "15643249@chat.skillz.com", "15550929@chat.skillz.com", "20842529@chat.skillz.com", "48178115@chat.skillz.com", "62393530@chat.skillz.com", "37172470@chat.skillz.com", "19925798@chat.skillz.com", "68727473@chat.skillz.com", "18303590@chat.skillz.com", "47350879@chat.skillz.com", "71665163@chat.skillz.com", "25325510@chat.skillz.com", "47907443@chat.skillz.com", "21710348@chat.skillz.com", "25339760@chat.skillz.com", "12959623@chat.skillz.com", "41438543@chat.skillz.com", "41481919@chat.skillz.com", "72621740@chat.skillz.com", "16242034@chat.skillz.com", "61225504@chat.skillz.com", "18456864@chat.skillz.com", "14688690@chat.skillz.com", "8817662@chat.skillz.com", "38566579@chat.skillz.com", "11338313@chat.skillz.com", "38596512@chat.skillz.com", "46910420@chat.skillz.com", "47060194@chat.skillz.com", "59207162@chat.skillz.com", "18051462@chat.skillz.com", "25000144@chat.skillz.com", "22405075@chat.skillz.com", "18099391@chat.skillz.com", "66611346@chat.skillz.com", "66361397@chat.skillz.com", "12877394@chat.skillz.com"]
  }
  mod_disco: {}
  mod_pres_counter:
    count: 100
    interval: 60
  mod_privacy: {}
  mod_vcard:
    search: true
  mod_admin_extra: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 10
    c2s_max_auth_failures: 200
  mod_http_bind: {}
  mod_mam: {}
  mod_metrics: {}
  mod_muc:
    access:
      - allow
    access_admin:
      allow: admin
    access_create: muc_create
    access_persistent: muc_create
    history_size: 200
    max_users: 10000
    max_user_conferences: 200
    max_room_id: 1024
    max_room_name: 1024
    max_room_desc: 2048
    min_message_interval: 0.4
    min_presence_interval: 0
    max_users_presence: 1000
    default_room_options:
      allow_change_subj: false
      allow_private_messages: true
      allow_query_users: true
      allow_visitor_status: true
      anonymous: true
      captcha_protected: false
      logging: true
      mam: true
      max_users: 10000
      members_by_default: true
      members_only: false
      moderated: true
      password_protected: false
      persistent: true
      public: true
      public_list: true
      presence_broadcast: {}
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_private:
    use_cache: false
  mod_register:
    ip_access: trusted_network
    access: register
  mod_roster: {}
