##
## Modules enabled in all ejabberd virtual hosts.
##
modules:
  mod_blocking: {} # requires mod_privacy
  mod_block_incoming: {
    blocking_users: ["test2", "test3", "11339339", "20361620", "12669429", "97789891", "67115158", "40890859", "50447625", "26581865", "41241278", "14462266", "33411470", "29450014", "32704697", "15643249", "15550929", "20842529", "48178115", "62393530", "37172470", "19925798", "68727473", "18303590", "47350879", "71665163", "25325510", "47907443", "21710348", "25339760", "12959623", "41438543", "41481919", "72621740", "16242034", "61225504", "18456864", "14688690", "8817662", "38566579", "11338313", "38596512", "46910420", "47060194", "59207162", "18051462", "25000144", "22405075", "18099391", "66611346", "66361397", "12877394"]
  }
  mod_disco: {}
  mod_pres_counter:
    count: 100
    interval: 60
  mod_privacy: {}
  mod_vcard:
    search: true
  mod_admin_extra: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 10
    c2s_max_auth_failures: 200
  mod_http_bind: {}
  mod_mam: {}
  mod_metrics: {}
  mod_muc:
    access:
      - allow
    access_admin:
      allow: admin
    access_create: muc_create
    access_persistent: muc_create
    history_size: 200
    max_users: 10000
    max_user_conferences: 200
    max_room_id: 1024
    max_room_name: 1024
    max_room_desc: 2048
    min_message_interval: 0.4
    min_presence_interval: 0
    max_users_presence: 1000
    default_room_options:
      allow_change_subj: false
      allow_private_messages: true
      allow_query_users: true
      allow_visitor_status: true
      anonymous: true
      captcha_protected: false
      logging: true
      mam: true
      max_users: 10000
      members_by_default: true
      members_only: false
      moderated: true
      password_protected: false
      persistent: true
      public: true
      public_list: true
      presence_broadcast: {}
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_private:
    use_cache: false
  mod_register:
    ip_access: trusted_network
    access: register
  mod_roster: {}
