language: "en"
allow_contrib_modules: true

# Logging
include_config_file: logging.yaml

# Hosts, populated by ejabberd helm chart virtualHosts value
include_config_file: config/hosts.yaml

# Listeners
include_config_file: config/listeners.yaml

# API Permissions
include_config_file: config/api-permissions.yaml

# Access Rules
include_config_file: config/access-rules.yaml

# Access Control Lists, populated by ejabberd helm chart virtualHosts value
include_config_file: config/access-control-lists.yaml

# Authentication, populated by ejabberd helm chart virtualHosts value
include_config_file: config/auth.yaml

# Mysql, populated by ejabberd helm chart mysqlAddress value
include_config_file: config/mysql.yaml

# Modules
include_config_file: config/modules.yaml
