##
## Modules enabled in all ejabberd virtual hosts.
##
modules:
  mod_blocking: {} # requires mod_privacy
  mod_disco: {}
  mod_pres_counter:
    count: 100
    interval: 60
  mod_privacy: {}
  mod_vcard:
    search: true
  # ModBeamStats: {}
  # mod_pottymouth:
  #   blacklists:
  #     default: /home/ejabberd/.ejabberd-modules/sources/mod_pottymouth/blacklist/blacklist_en.txt
  #     en: /home/ejabberd/.ejabberd-modules/sources/mod_pottymouth/blacklist/blacklist_en.txt
  # ModPushSkillz:
  #   rabbit_url: "amqp://RABBITMQ_AUTH@rabbit.qa.skillz.com:5672/skillz" # Populated by a secret macro
  mod_admin_extra: {}
  mod_fail2ban:
    c2s_auth_ban_lifetime: 10
    c2s_max_auth_failures: 200
  mod_http_bind: {}
  mod_mam: {}
  mod_metrics: {}
  mod_muc:
    access:
    - allow
    access_admin:
      allow: admin
    access_create: muc_create
    access_persistent: muc_create
    history_size: 200
    max_users: 10000
    max_user_conferences: 50
    max_room_id: 1024
    max_room_name: 1024
    max_room_desc: 2048
    min_message_interval: 0.4
    min_presence_interval: 4
    max_users_presence: 200
    default_room_options:
      allow_change_subj: false
      allow_private_messages: true
      allow_query_users: false
      allow_visitor_status: false
      anonymous: true
      captcha_protected: false
      logging: true
      mam: true
      max_users: 10000
      members_by_default: true
      members_only: false
      moderated: true
      password_protected: false
      persistent: true
      public: true
      public_list: false
      presence_broadcast: {}
  mod_muc_admin: {}
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_private:
    use_cache: false
  mod_register:
    ip_access: trusted_network
    access: register
  mod_roster: {}
