###.  ==============
###'  AUTHENTICATION

##
## auth_method: Method used to authenticate the users.
## The default method is the internal.
## If you want to use a different method,
## comment this line and enable the correct ones.
##
## We have two hosts, one for admin and one for users.  They have different auth methods.

auth_use_cache: false
append_host_config:
  "chat-admin.qa.skillz.com":
    auth_method: internal

append_host_config:
  "chat.qa.skillz.com":
    auth_method: http
    auth_opts:
      host: "http://api-gateway-internal-islay.qa.us-west-2:10010" # Because qa-app-us-west-2 relies on vpc peering, we cannot resolve .islay records and this alias was created manually
      connection_pool_size: 8
      connection_opts: []
      path_prefix: "/chat-auth/"

default_db: sql

sql_type: mysql
sql_server: $(RDS_DB_ENDPOINT)

sql_port: 3306
sql_database: "ejabberd"
sql_username: MYSQL_USERNAME # Populated from a secret macro
sql_password: MYSQL_PASSWORD # Populated from a secret macro
sql_keepalive_interval: 60
sql_start_interval: 5
sql_pool_size: 10
